excel_headers:
- SAMPLE
- HGVS
- GENE/LOCUS
- GENE/LOCUS DESCRIPTION
- TOTAL LOCUS DEPTH
- VARIANT HETEROPLASMY
- ALT DEPTH
- REF DEPTH
- TOTAL SAMPLE DEPTH
- VARIANT QUALITY
- TIER
- COHORT COUNT
- COHORT FREQUENCY
- CHR
- POS
- REF
- ALT
- QUAL
- FILTER
- MQM_INFO
- MQMR_INFO
- QA_INFO
- QR_INFO
- SAF_INFO
- SAR_INFO
- SRF_INFO
- SRR_INFO
- SBR_INFO
- SBA_INFO
- POS_FILTER
- SBR_FILTER
- SBA_FILTER
- MQMR_FILTER
- AQR_FILTER
- COMMERCIAL PANELS
- PHYLOTREE HAPLOTYPE
- MITOTIP SCORE
- MITOTIP PERCENTILE
- MITOTIP INTERPRETATION
- ANTICODON
- ALLELE FREQUENCY MITOMAP
- DISEASE MITOMAP
- MGRB FREQUENCY
- MGRB FILTER
- MGRB AC
- MGRB AN
- PHYLOTREE MUT
- LOCUS MITOMAP
- NUMBER OF REFERENCES MITOMAP
- VARIANT AMINO ACID CHANGE MITOMAP
- CODON POSITION MITOMAP
- CODON NUMBER MITOMAP
- NUM DISEASE REFERENCES MITOMAP
- RNA MITOMAP
- HOMOPLASMY MITOMAP
- HETEROPLASMY MITOMAP
- STATUS MITOMAP
- DISEASE AMINO ACID CHANGE MITOMAP
- GENBANK FREQUENCY MITOMAP
- GT_FORMAT
- QR_FORMAT
- AQR_FORMAT
- QA_FORMAT
- AQA_FORMAT
- INFO
- FORMAT
vcf_headers:
  annotations:
    GenBank_frequency_mitomap: GENBANK FREQUENCY MITOMAP
    MGRB_AC: MGRB AC
    MGRB_AN: MGRB AN
    MGRB_FILTER: MGRB FILTER
    MGRB_frequency: MGRB FREQUENCY
    MitoTip_interpretation: MITOTIP INTERPRETATION
    MitoTip_percentile: MITOTIP PERCENTILE
    MitoTip_score: MITOTIP SCORE
    RNA_mitomap: RNA MITOMAP
    anticodon: ANTICODON
    codon_number_mitomap: CODON NUMBER MITOMAP
    codon_position_mitomap: CODON POSITION MITOMAP
    commercial_panels: COMMERCIAL PANELS
    disease_amino_acid_change_mitomap: DISEASE AMINO ACID CHANGE MITOMAP
    disease_mitomap: DISEASE MITOMAP
    heteroplasmy_mitomap: HETEROPLASMY MITOMAP
    homoplasmy_mitomap: HOMOPLASMY MITOMAP
    locus_mitomap: LOCUS MITOMAP
    num_disease_references_mitomap: NUM DISEASE REFERENCES MITOMAP
    num_references_mitomap: NUMBER OF REFERENCES MITOMAP
    phylotree_haplotype: PHYLOTREE HAPLOTYPE
    phylotree_mut: PHYLOTREE MUT
    status_mitomap: STATUS MITOMAP
    variant_amino_acid_change_mitomap: VARIANT AMINO ACID CHANGE MITOMAP
  format:
    AO: ALT DEPTH
    AQA: AQA_FORMAT
    AQR: AQR_FORMAT
    AQR_filter: AQR_FILTER
    DP: TOTAL SAMPLE DEPTH
    GT: GT_FORMAT
    MQMR_filter: MQMR_FILTER
    POS_filter: POS_FILTER
    QA: QA_FORMAT
    QR: QR_FORMAT
    RO: REF DEPTH
    SBA_filter: SBA_FILTER
    SBR_filter: SBR_FILTER
    VAF: VARIANT HETEROPLASMY
    q: VARIANT QUALITY
    tier: TIER
  info:
    DP: TOTAL LOCUS DEPTH
    Description: GENE/LOCUS DESCRIPTION
    MQM: MQM_INFO
    MQMR: MQMR_INFO
    Map_Locus: GENE/LOCUS
    QA: QA_INFO
    QR: QR_INFO
    SAF: SAF_INFO
    SAR: SAR_INFO
    SBA: SBA_INFO
    SBR: SBR_INFO
    SRF: SRF_INFO
    SRR: SRR_INFO